version: '3.8'

volumes:
  mongo_data:

services:
  mongo_db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: books
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  api:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env                  
    depends_on:
      - mongo_db